name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build-test (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Verify
        run: |
          mvn -B -ntp -q -DskipITs verify -pl jHash-core -am

      - name: Upload surefire & jacoco reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-jdk${{ matrix.java }}
          path: |
            **/target/surefire-reports/**
            **/target/site/jacoco/**

  style:
    name: checkstyle (JDK 17)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Checkstyle
        run: mvn -B -ntp -q checkstyle:check -pl jHash-core -am